name: Music Genre Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    - name: Recreate the secret file
      run: |
        mkdir -p build_dataset
        echo '${{ secrets.CLIENT_SECRET_DATA }}' > build_dataset/client_secrets.json

    - name: Run Model Processing
      run: | 
